'use strict';
let revision=1, timer=null, pending=false, renderedModel='', engineSession=null;
const $=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function headers(){return {'Content-Type':'application/json','X-Engine-Token':$('token').value};}
async function request(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:headers(),body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||data.status||'Request failed');return data;}
function render(s){if(engineSession===s.engineSessionId && s.revision<revision)return;engineSession=s.engineSessionId;revision=s.revision;$('connection').textContent='CONNECTED · Engine running';$('metrics').replaceChildren(...[
 `Sample clock ${s.sampleClock}`,`MIDI messages ${s.midiCount}`,`Active notes ${s.activeNotes}`,`Maximum callback ${s.maxCallbackUs.toFixed(1)} µs`,`Late blocks ${s.lateBlocks}`].map(v=>node('span',v)));
 $('last-midi').textContent=`Last MIDI · sample ${s.lastEvent[0]} · status ${s.lastEvent[1]} · number ${s.lastEvent[2]} · value ${s.lastEvent[3]}`;
 const model=JSON.stringify([s.phrases,s.instruments,s.switches.map(v=>({...v,step:0}))]);for(const sw of s.switches){const el=document.querySelector(`[data-switch-id="${sw.id}"] .step`);if(el)el.textContent=`STEP ${sw.step} / ${sw.length}`;}if(model===renderedModel)return;renderedModel=model;
 $('phrases').replaceChildren(...s.phrases.map(p=>{const n=node('div',`PHRASE ${p.id}`,'phrase');n.append(node('small',`${p.events} events · ${p.mode===0?'LOOP':'ONCE / HOLD'} · TIME ×${p.timeDecay.toFixed(2)}`));for(const [label,action] of [['PLAY','phrase_play'],['REC / OVERDUB','phrase_record'],['FINISH REC','phrase_finish']]){const b=node('button',label);b.addEventListener('click',()=>command({action,phraseId:p.id}));n.append(b);}return n;}));
 $('instruments').replaceChildren(...s.instruments.map(i=>{const n=node('article',undefined,'instrument');const title=node('div',i.name||`INSTRUMENT ${i.id}`);title.append(node('small',i.enabled?' · ON':' · OFF'));const routing=node('div',`MIDI IN ${i.input||'ALL'} → OUT ${i.output||'ORIGINAL'}`,'routing');const volume=node('div',`VOLUME ${i.level}`);const rail=node('div',undefined,'rail');const fill=node('span');fill.style.width=`${i.level/127*100}%`;rail.append(fill);volume.append(rail);n.append(title,routing,volume);const chain=node('div',undefined,'transformers');for(const tf of i.transformers||[])chain.append(node('p',`${['','TRANSPOSE','RANGE','POLYPHONY','VELOCITY','ARP','CC MOD'][tf.type]||'MODULE'} · ID ${tf.id} · ${tf.enabled?'ON':'BYPASS'}`));n.append(chain);for(const [field,max] of [['input',16],['output',16],['level',127],['enabled',1]]){const l=node('label',field.toUpperCase());const input=node('input');input.type='number';input.min=0;input.max=max;input.value=i[field];input.addEventListener('change',()=>command({action:field==='enabled'?'instrument_enabled':'instrument_route',instrumentId:i.id,field,value:Number(input.value)}));l.append(input);n.append(l);}return n;}));
 $('switches').replaceChildren(...s.switches.map(sw=>{const n=node('article',undefined,'switch');n.dataset.switchId=sw.id;n.append(node('h3',sw.name||`SWITCH ${sw.id}`),node('p',`${sw.type===0?'PHRASE':'SPECIAL'} · ID ${sw.id}`),node('p',`${sw.kind===1?'NOTE':sw.kind===2?'CC':'UNASSIGNED'} ${sw.number} · CH ${sw.channel}`));n.append(node('p',`STEP ${sw.step} / ${sw.length}`,'step'));const tests=node('div',undefined,'tests');for(const gesture of ['tap','double','hold']){const b=node('button',`TEST ${gesture.toUpperCase()}`);b.dataset.valid=sw.enabled?'1':'0';b.disabled=!sw.enabled;b.addEventListener('click',()=>command({action:'test',switchId:sw.id,gesture}));tests.append(b);}const hardware=node('button','SIMULATE FOOTSWITCH','hardware');hardware.disabled=sw.kind!==1;hardware.dataset.valid=sw.kind===1?"1":"0";hardware.addEventListener('click',async()=>{if(await command({action:'midi',channel:sw.channel,note:sw.number,value:100}))await command({action:'midi',channel:sw.channel,note:sw.number,value:0});});n.append(tests,hardware);return n;}));
}
async function refresh(){try{render(await request('/api/v1/state'));$('error').textContent='';}catch(e){$('connection').textContent='DISCONNECTED · Engine continues independently';$('error').textContent=e.message;}}
async function command(value){if(pending)return false;pending=true;for(const b of document.querySelectorAll('.tests button,.hardware,#panic'))b.disabled=true;try{render(await request('/api/v1/command',{protocolVersion:1,expectedRevision:revision,...value}));$('error').textContent='';return true;}catch(e){$('error').textContent=e.message;return false;}finally{pending=false;$('panic').disabled=false;for(const b of document.querySelectorAll('.tests button'))b.disabled=b.dataset.valid!=='1';for(const b of document.querySelectorAll('.hardware'))b.disabled=b.dataset.valid!=='1';}}
$('panic').addEventListener('click',()=>command({action:'panic'}));$('connect').addEventListener('click',()=>{renderedModel='';refresh();});
let ws=null, reconnect=null;
function connectStream(){if(ws)ws.close();ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/v1/ws`);ws.onopen=()=>ws.send(JSON.stringify({token:$('token').value}));ws.onmessage=e=>{try{if(!pending)render(JSON.parse(e.data));}catch(err){$('error').textContent=err.message;}};ws.onclose=()=>{$('connection').textContent='DISCONNECTED · Engine continues independently';reconnect=setTimeout(connectStream,1000);};ws.onerror=()=>ws.close();}
$('connect').addEventListener('click',()=>{clearTimeout(reconnect);if(ws){ws.onclose=null;ws.close();}connectStream();});
async function patch(action){if(pending)return;pending=true;try{const data=await request(`/api/v1/patch/${action}`,{slot:Number($('patch-slot').value),expectedRevision:revision});$('patch-status').textContent=action==='save'?'PATCH SAVED':'PATCH LOADED';if(data.revision)render(data);}catch(e){$('error').textContent=e.message;}finally{pending=false;refresh();}}
$('save-patch').addEventListener('click',()=>patch('save'));$('load-patch').addEventListener('click',()=>patch('load'));
refresh();connectStream();timer=setInterval(()=>{if(!pending&&(!ws||ws.readyState!==WebSocket.OPEN))refresh();},1000);
// Browser timers refresh status only; they never schedule or generate phrase events.
